services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: mdashifreza111@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8001:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540" # RedisInsight web UI port
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/db
volumes:
  pgadmin_data:
  redisinsight-data:
